# Generated by Django 5.2.6 on 2025-12-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devkey', models.CharField(max_length=64)),
                ('devmac', models.CharField(blank=True, max_length=17, null=True)),
                ('phyname', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_ap', models.BooleanField(db_index=True, default=False)),
                ('is_client', models.BooleanField(db_index=True, default=False)),
                ('ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=20, null=True)),
                ('encryption', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('probed_ssids', models.JSONField(blank=True, null=True)),
                ('advertised_ssids', models.JSONField(blank=True, null=True)),
                ('strongest_signal', models.IntegerField(blank=True, null=True)),
                ('avg_signal', models.FloatField(blank=True, null=True)),
                ('last_signal', models.IntegerField(blank=True, null=True)),
                ('first_time', models.DateTimeField(blank=True, null=True)),
                ('last_time', models.DateTimeField(blank=True, null=True)),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('max_lon', models.FloatField(blank=True, null=True)),
                ('avg_lat', models.FloatField(blank=True, null=True)),
                ('avg_lon', models.FloatField(blank=True, null=True)),
                ('bytes_data', models.BigIntegerField(blank=True, null=True)),
                ('packets_seen', models.BigIntegerField(blank=True, null=True)),
                ('clients_count', models.IntegerField(blank=True, null=True)),
                ('device_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scans',
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_sec', models.IntegerField(db_index=True)),
                ('ts_usec', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sourcemac', models.CharField(blank=True, max_length=17, null=True)),
                ('destmac', models.CharField(blank=True, max_length=17, null=True)),
                ('transmac', models.CharField(blank=True, max_length=17, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('signal', models.IntegerField(blank=True, null=True)),
                ('datarate', models.FloatField(blank=True, null=True)),
                ('packet_len', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('datasource', models.CharField(blank=True, max_length=50, null=True)),
                ('phyname', models.CharField(blank=True, max_length=50, null=True)),
                ('packet_json', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packets', to='kismet.device')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='kismet.scan')),
            ],
            options={
                'db_table': 'packets',
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('devmac', models.CharField(blank=True, max_length=17, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kismet.device')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='kismet.scan')),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='kismet.scan'),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('typestring', models.CharField(blank=True, max_length=50, null=True)),
                ('definition', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('interface', models.CharField(blank=True, max_length=50, null=True)),
                ('packet_count', models.BigIntegerField(default=0)),
                ('error_count', models.BigIntegerField(default=0)),
                ('json', models.JSONField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='kismet.scan')),
            ],
            options={
                'db_table': 'datasources',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mac', models.CharField(db_index=True, max_length=17)),
                ('bssid', models.CharField(blank=True, max_length=17, null=True)),
                ('bssid_key', models.CharField(blank=True, max_length=64, null=True)),
                ('is_associated', models.BooleanField(default=False)),
                ('client_type', models.CharField(blank=True, max_length=50, null=True)),
                ('decrypted', models.BooleanField(default=False)),
                ('datasize', models.BigIntegerField(default=0)),
                ('num_retries', models.IntegerField(default=0)),
                ('first_time', models.DateTimeField(blank=True, null=True)),
                ('last_time', models.DateTimeField(blank=True, null=True)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lon', models.FloatField(blank=True, null=True)),
                ('client_json', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_clients', to='kismet.device')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='kismet.scan')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('devmac', models.CharField(blank=True, max_length=17, null=True)),
                ('header', models.CharField(blank=True, max_length=200, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='kismet.scan')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['scan'], name='devices_scan_id_bc7818_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['devmac'], name='devices_devmac_a96e39_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['type'], name='devices_type_e90211_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['avg_lat', 'avg_lon'], name='devices_avg_lat_2c99c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('scan', 'devkey'), name='unique_device_per_scan'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_mac'], name='clients_client__41f0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['bssid'], name='clients_bssid_729d47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('scan', 'device', 'client_mac')},
        ),
    ]
